slidewikiplatform:
  image: slidewiki/platform:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - PORT=80
    - VIRTUAL_HOST=platform.experimental.slidewiki.org
    - LETSENCRYPT_HOST=platform.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_DISCUSSION=https://discussionservice.experimental.slidewiki.org
    - SERVICE_URL_ACTIVITIES=https://activitiesservice.experimental.slidewiki.org
    - SERVICE_URL_NOTIFICATION=https://notificationservice.experimental.slidewiki.org
    - SERVICE_URL_USER=https://userservice.experimental.slidewiki.org
    - SERVICE_URL_IMPORT=https://importservice.experimental.slidewiki.org
    - SERVICE_URL_FILE=https://fileservice.experimental.slidewiki.org
    - SERVICE_URL_TAG=https://tagservice.experimental.slidewiki.org
    - SERVICE_URL_SEARCH=https://searchservice.experimental.slidewiki.org
    - SERVICE_URL_PDF=https://pdfservice.experimental.slidewiki.org
    - SERVICE_VAR_IMPORT_HOST=importservice.experimental.slidewiki.org
    - SERVICE_USER_APIKEY=2cbc621f86e97189239ee8c4c80b10b3a935b8a9f5db3def7b6a3ae7c4b75cb5
    - SERVICE_USER_PRIVATE_RECAPTCHA_KEY=6LdNLyYTAAAAAFMC0J_zuVI1b9lXWZjPH6WLe-vJ
    - SERVICE_USER_PUBLIC_RECAPTCHA_KEY=6LdNLyYTAAAAAINDsVZRKG_E3l3Dvpp5sKboR1ET
